### ISSUE TITLE
Clicking Image Upload 

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#224]
```[Vue warn]: Cannot set reactive property on undefined, null, or primitive value: undefined

[Vue warn]: Error in v-on handler: "TypeError: Cannot use 'in' operator to search for 'gif' in undefined"

found in

---> <FormMultiColumn>
       <VueFormRenderer>
         <TaskScreen> at resources/js/tasks/components/TaskForm.vue
           <Root>

TypeError: Cannot use 'in' operator to search for 'gif' in undefined
```

It occurs when I try to click a button on a form that uses images. There is custom CSS for the images.

This prevents the user from proceeding past the displayed Screen.

**Comment by chipit24** [comment]
@velkymx I tried a few different combinations of forms with images, file uploads, and tables (multi-column) and couldn't reproduce the above error. What does the form look like that produces this bug?

**Comment by velkymx** [comment]
Let me get a video from QA

**Comment by velkymx** [comment]
QA says the is already resolved. Closing

**Comment by PMQABen** [comment]
Not resolved. I can still make it happen with the following Process:
[qa_test-(1min timer).spark.txt](https://github.com/ProcessMaker/spark-screen-builder/files/3258428/qa_test-.1min.timer.spark.txt)

(remove the .txt extension)

**Comment by chipit24** [comment]
@velkymx  @PMQABen This bug appears on any element, not just with images or tables. It's because the field name is `hmmyes.001.gif`; and field names are parsed using [`vue-deepset`](https://github.com/bhoriuchi/vue-deepset), which interprets the dots as delimiters for object properties and numbers as index values. And in this case, `001` is not accepted as a valid index.

The reason for this, is to allow nested properties. For example:
<img width="567" alt="Screen Shot 2019-06-05 at 4 02 08 PM" src="https://user-images.githubusercontent.com/7561061/58986438-60850b00-87ab-11e9-8407-6d55abc1d5c0.png">
<img width="1057" alt="Screen Shot 2019-06-05 at 4 02 24 PM" src="https://user-images.githubusercontent.com/7561061/58986431-5e22b100-87ab-11e9-8cb6-68b07f1efae9.png">

There might be a few different ways around this:
* Validate variable/field name as a valid "object path" before using it.
* If the object path isn't valid, treat it as a "flat" string, e.g.: `{ "name.first": "Rob" }`.

@velkymx What are your thoughts on this? I'm assuming this is intended behaviour, and if the users are expected to treat the variable name as a potential path, it should be documented and validated.

**Comment by chipit24** [comment]
I did notice a related bug though. If the value is left blank, it submits the "flat" values instead of using vue-deepset:
```json
{
  "submit": "yes",
  "name.first": "",
  "name.last": ""
}
```

**Comment by velkymx** [comment]
@chipit24 for the file upload it should treat the filename as a string and not as an object. It should be "upload1":"file.name.ext"

**Comment by chipit24** [comment]
@velkymx That seems to work as expected; if I upload an image with the name `hmmyes.001.gif`, it is correctly parsed and given a variable name of `hmmyes`. The problem is, there's nothing stopping a user from manually entering a variable/field name like `hmmyes.001.gif`. So we need to do one of two things:
* Validate variable names
* Treat invalid variable names as strings

The 1st option above is easier to implement, and may lead to better UX (users may not know when their variable will be treated as a string or path, whereas it's more clear when it's always treated as a path and validated).
