### ISSUE TITLE
Select Lists: Default Value

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#646]
When a default value is set for the date fields the select is not set to the value. In addition the radio and checkboxes should be selected if there is a matching value.

**Comment by danloa** [comment]
This issue is resolved in vue-form-elements with this PR:
https://github.com/ProcessMaker/vue-form-elements/pull/170

**Comment by ZLTM** [comment]
Default value still won't show on today's pull from screen-builder dev branch

**Comment by PMQABen** [comment]
Mustache syntax seems to work, but straight text does not work.

**Comment by PMQABen** [comment]
Well that's a mea culpa. After Dante explained how this stuff works, I can verify that select list default values are working.
